### ISSUE TITLE
I do not understand how to use it for payments with Fawry in flutter

### ISSUE THREAD

**Issue by chakertriangle** [ShadyBoshra2012/flutter_fawry_pay#1]
Hello, how can I use it, does it depend on the Fawry plugin, or doesn't it, I'm getting errors when trying to run the example main.dart because of no keys.dart file exists and I do not know how to write it up.

**Comment by ShadyBoshra2012** [comment]
Hello @chakertriangle, glad to use the plugin.

As I mentioned in docs, you should contact with FawryPay service provider to get your merchantID, and use it in plugins. 

File keys.dart is just a file contains my private key, so I should NOT share. 

It does depent on FawryPay native plugins? Sure it does.
