### ISSUE TITLE
can not setup it.

### ISSUE THREAD

**Issue by yousseftaha2001** [ShadyBoshra2012/flutter_fawry_pay#3]
> 
![s1](https://user-images.githubusercontent.com/76664153/125172348-8fa3ad00-e1b9-11eb-9ecb-23b019ea23e0.PNG)
![s2](https://user-images.githubusercontent.com/76664153/125172350-92060700-e1b9-11eb-8f7f-6019a5bbe753.PNG)
الملف مش موجود عشان احمله

**Comment by ShadyBoshra2012** [comment]
Thanks for your open this issue, you are right, the link is broken after the latest update. The file will your find here: https://github.com/ShadyBoshra2012/flutter_fawry_pay/blob/master/flutter_fawry_pay/example/android/app/libs/fawryplugin-release.aar
