### ISSUE TITLE
How to Skip step 2 in payment

### ISSUE THREAD

**Issue by mohamed-elbendary** [ShadyBoshra2012/flutter_fawry_pay#4]
I want to skip step 2 in payment and go to step 3 after pressed the Fawry button to choose the payment method directly and pay for the product

**Comment by ShadyBoshra2012** [comment]
Hello @mohamed-elbendary ,

Unfortunately, your request is out of my package. This is related to Native Android and iOS SDKs of FawryPay, and I can change nothing in it. You can contact Fawry, and try to resolve this problem with them.
