### ISSUE TITLE
flutter_fawry_pay for web 

### ISSUE THREAD

**Issue by HassanShaban** [ShadyBoshra2012/flutter_fawry_pay#7]
in your example when press in init for card token this error appear

Error: Error Occurred: Code: Unimplemented. Message: null. Details: flutter_fawry_pay for web doesn't implement 'initialize_card_tokenizer'

**Comment by ShadyBoshra2012** [comment]
FawryPay is not for Web.

**Comment by HassanShaban** [comment]
ok fine remove web platform from pub.dev
